### ISSUE TITLE
Unity Core Module

### ISSUE THREAD

**Issue by Kaspoehh** [merijndejonge/DgmlBuilder#12]
![image](https://user-images.githubusercontent.com/32570212/91856817-592b0680-ec67-11ea-93fd-f64332148ff7.png)
 When referencing the project in Program.cs, I'm getting this error.

**Comment by merijndejonge** [comment]
Hello @Kaspoehh,
Thanks for reporting the issue.
I think you are referencing the Typesvisualizer project in Program.cs, right?
Please understand that TypesVisualizer is an example of how DgmlBuilder can be used. It is not intended as a library that can visualize types of any project. The reason is that I do not fully understand how to load assemblies for just reflection. I think that your case demonstrates that the loading mechanism that I used is not always working. If you happen to know a better implementation, I would welcome a pull request.

**Comment by Kaspoehh** [comment]
Hi, 
I fixed it by copying the UnityEngine.Coremodule from the unity data\managed folder in program files in the C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.7 folder. And then just link the project.
